<?php
require_once 'scraper.search.inc';

/**
 * @file
 * Scraper Twitter - find some emails.. module.
 *
 * @author: Owen Williams
 *
 */

/**
* Implements hook_menu().
*/
function scraper_menu() {
  $items['scraper/search'] = array(
    'title' => 'Searcher',
    'page callback' => 'scraper_search_ajax',
    'access callback' => TRUE,
    'page arguments' => array(),
    'type' => MENU_CALLBACK,
    // 'file' => 'models_forms.create.inc',
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function scraper_block_info() {
  $blocks['search_form'] = array(
    'info' => t('Scraper - search block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function scraper_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'search_form':
      $block['subject'] = t('Searcher');
      $block['content'] = scraper_searcher();
    break;
  }
  return $block;
}

function scraper_searcher() {
  $search_form = drupal_get_form('scraper_search_form');
  return drupal_render($search_form);
}

function scraper_search_ajax() {
  $params = json_decode(file_get_contents('php://input'), TRUE);

  if (!empty($params['search_terms'])) {

  $terms = str_replace(',', ' ', $params['search_terms']);
  $terms = str_replace('  ', ' ', $terms);
  $terms = urlencode($terms);

  /** Set access tokens here - see: https://dev.twitter.com/apps/ **/
    $settings = array(
      'oauth_access_token' => "328416372-LKKl8TQMmcRLkbOuF31f4oNPcoKn4vKEBHqUmw9g",
      'oauth_access_token_secret' => "7nzP4qbuNeqCvE7QUNHJ6AXdURubXie22JoiTk",
      'consumer_key' => "C35vWXtEYi2ND6E1DEtMA",
      'consumer_secret' => "Bglu3sttmouKbOVdFZTMKCFTZlPV6IM8NBduDBD6UJU"
    );

    /** Note: Set the GET field BEFORE calling buildOauth(); **/
    $url = 'https://api.twitter.com/1.1/search/tweets.json';
    $getfield = '?q=%40twitterapi';

    // around UK >
    // 37.781157,-122.398720,1mi
    // 54.213861,-4.548340,576.7529226763561km

    // $getfield = '?q=' . $terms . '&count=100&lang=en-gb&geocode=54.213861,-4.548340,576.7529226763561km';
    // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&until=2016-06-16';
    // $requestMethod = 'GET';
    // $twitter = new TwitterAPIExchange($settings);
    // $result = $twitter->setGetfield($getfield)
    //    ->buildOauth($url, $requestMethod)
    //    ->performRequest();

    $results_array = array();

    $now = date('Y-m-d', strtotime('now'));

    // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100';
    $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100';
    $requestMethod = 'GET';
    $twitter = new TwitterAPIExchange($settings);
    $result = $twitter->setGetfield($getfield)
       ->buildOauth($url, $requestMethod)
       ->performRequest();

    $res = json_decode($result);
    $count = sizeof($res->statuses) - 1;
    $last_id = ($res->statuses[$count]->id - 1);
    $results_array[] = $res->statuses;

    for ($i=1; $i <= 8; $i++) {

      $now = date('Y-m-d', strtotime("$now - 1 day"));

      $getfield = '?q=' . $terms . '&result_type=*recent&count=100&until=' . $now;
      // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&max_id=' . $last_id;
      $requestMethod = 'GET';
      $twitter = new TwitterAPIExchange($settings);
      $result = $twitter->setGetfield($getfield)
         ->buildOauth($url, $requestMethod)
         ->performRequest();

      $res = json_decode($result);
      $count = sizeof($res->statuses) - 1;
      $last_id = ($res->statuses[$count]->id - 1);
      $results_array[] = $res->statuses;

      $getfield = '?q=' . $terms . '&result_type=*popular&count=100&until=' . $now;
      // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&max_id=' . $last_id;
      $requestMethod = 'GET';
      $twitter = new TwitterAPIExchange($settings);
      $result = $twitter->setGetfield($getfield)
         ->buildOauth($url, $requestMethod)
         ->performRequest();

      $res = json_decode($result);
      $results_array[] = $res->statuses;


      // $getfield = '?q=' . $terms . '&result_type=*mixed&count=100&until=' . $now;
      // // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&max_id=' . $last_id;
      // $requestMethod = 'GET';
      // $twitter = new TwitterAPIExchange($settings);
      // $result = $twitter->setGetfield($getfield)
      //    ->buildOauth($url, $requestMethod)
      //    ->performRequest();

      // $res = json_decode($result);
      // $results_array[] = $res->statuses;

      // dpm($last_id, 'last id...');
    }

    print_r(json_encode($results_array));

  }

}

function scraper_init() {

  /** Set access tokens here - see: https://dev.twitter.com/apps/ **/
  $settings = array(
    'oauth_access_token' => "328416372-LKKl8TQMmcRLkbOuF31f4oNPcoKn4vKEBHqUmw9g",
    'oauth_access_token_secret' => "7nzP4qbuNeqCvE7QUNHJ6AXdURubXie22JoiTk",
    'consumer_key' => "C35vWXtEYi2ND6E1DEtMA",
    'consumer_secret' => "Bglu3sttmouKbOVdFZTMKCFTZlPV6IM8NBduDBD6UJU"
  );

  $oo = 'fitness, blogger';
  $terms = str_replace(',', ' ', $oo);
  $terms = str_replace('  ', ' ', $terms);
  $terms = urlencode($terms);

  /** Set access tokens here - see: https://dev.twitter.com/apps/ **/
    $settings = array(
      'oauth_access_token' => "328416372-LKKl8TQMmcRLkbOuF31f4oNPcoKn4vKEBHqUmw9g",
      'oauth_access_token_secret' => "7nzP4qbuNeqCvE7QUNHJ6AXdURubXie22JoiTk",
      'consumer_key' => "C35vWXtEYi2ND6E1DEtMA",
      'consumer_secret' => "Bglu3sttmouKbOVdFZTMKCFTZlPV6IM8NBduDBD6UJU"
    );

    /** Note: Set the GET field BEFORE calling buildOauth(); **/
    $url = 'https://api.twitter.com/1.1/search/tweets.json';
    $getfield = '?q=%40twitterapi';

    // print_r($terms);

    // around UK >
    // 37.781157,-122.398720,1mi
    // 54.213861,-4.548340,576.7529226763561km

    // $results_array = array();

    // $now = date('Y-m-d', strtotime('now'));

    // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=3&until=' . $now;
    // $requestMethod = 'GET';
    // $twitter = new TwitterAPIExchange($settings);
    // $result = $twitter->setGetfield($getfield)
    //    ->buildOauth($url, $requestMethod)
    //    ->performRequest();

    // $res = json_decode($result);
    // $count = sizeof($res->statuses) - 1;
    // $last_id = ($res->statuses[$count]->id - 1);
    // $results_array[] = $res->statuses;

    // for ($i=1; $i <= 5; $i++) {

    //   $now = date('Y-m-d', strtotime("$now - 1 day"));

    //   $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=3&until=' . $now;
    //   // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=3&max_id=' . $last_id;
    //   $requestMethod = 'GET';
    //   $twitter = new TwitterAPIExchange($settings);
    //   $result = $twitter->setGetfield($getfield)
    //      ->buildOauth($url, $requestMethod)
    //      ->performRequest();

    //   $res = json_decode($result);
    //   $count = sizeof($res->statuses) - 1;
    //   $last_id = ($res->statuses[$count]->id - 1);
    //   $results_array[] = $res->statuses;
    //   // dpm($last_id, 'last id...');
    // }

    // dpm($results_array);



    // $getfield = '?q=' . $terms . '&count=100&lang=en-gb&geocode=54.213861,-4.548340,576.7529226763561km';

    // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&until=2016-06-16';
    // $requestMethod = 'GET';
    // $twitter = new TwitterAPIExchange($settings);
    // $result = $twitter->setGetfield($getfield)
    //    ->buildOauth($url, $requestMethod)
    //    ->performRequest();


    //    $res = json_decode($result);
    // dpm($res);


}
