<?php
require_once 'scraper.search.inc';

/**
 * @file
 * Scraper Twitter - find some emails.. module.
 *
 * @author: Owen Williams
 *
 */

/**
* Implements hook_menu().
*/
function scraper_menu() {
  $items['scraper/search'] = array(
    'title' => 'Searcher',
    'page callback' => 'scraper_search_ajax',
    'access callback' => TRUE,
    'page arguments' => array(),
    'type' => MENU_CALLBACK,
    // 'file' => 'models_forms.create.inc',
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function scraper_block_info() {
  $blocks['search_form'] = array(
    'info' => t('Scraper - search block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function scraper_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'search_form':
      $block['subject'] = t('Searcher');
      $block['content'] = scraper_searcher();
    break;
  }
  return $block;
}

function scraper_searcher() {
  $search_form = drupal_get_form('scraper_search_form');
  return drupal_render($search_form);
}

function scraper_search_ajax() {

  // curl -H "Content-Type: application/json" -X POST -d '{"startUrls":[{"key": "TEST", "value": "http://www.example.com"}]}' https://api.apifier.com/v1/wzHqPfZhWtuPXpX3f/crawlers/Twitter%20Scraper/execute?token=5iijWrGbJetJZ2ZhhqvbcBWg7

  $params = json_decode(file_get_contents('php://input'), TRUE);

  // print_r($params);

  if (!empty($params['search_terms'])) {
    if ($params['search_terms']['region'] == 'UK/Ireland') {
      $location = '&geocode=54.213861,-4.548340,576.7529226763561km';
    }
    if ($params['search_terms']['region'] == 'Europe') {
      $location = '&geocode=46.073231,26.015625,3045.5124816339926km';
    }
    if ($params['search_terms']['region'] == 'North America') {
      $location = '&geocode=37.718590,-101.953125,4022.1373212313893km';
    }
    if ($params['search_terms']['region'] == 'South America') {
      $location = '&geocode=-19.973349,-64.687500,4119.541746804172km';
    }
    if ($params['search_terms']['region'] == 'Australia') {
      $location = '&geocode=-25.799891,135.703125,16424.246km';
    }
    if ($params['search_terms']['region'] == 'Asia') {
      $location = '&geocode=31.353637,114.609375,5344.917381574208km';
    }
    if ($params['search_terms']['region'] == 'Global') {
      $location = '';
    }

    if ($params['search_terms']['searchtype'] == 'Recent') {
      $tweet_type = '*recent';
    }
    if ($params['search_terms']['searchtype'] == 'Mixed') {
      $tweet_type = '*mixed';
    }
    if ($params['search_terms']['searchtype'] == 'Popular') {
      $tweet_type = '*popular';
    }

    $terms = str_replace(',', ' ', $params['search_terms']['terms']);
    $terms = str_replace('  ', ' ', $terms);
    $terms = urlencode($terms);

    /** Set access tokens here - see: https://dev.twitter.com/apps/ **/
    $settings = array(
      'oauth_access_token' => "328416372-LKKl8TQMmcRLkbOuF31f4oNPcoKn4vKEBHqUmw9g",
      'oauth_access_token_secret' => "7nzP4qbuNeqCvE7QUNHJ6AXdURubXie22JoiTk",
      'consumer_key' => "C35vWXtEYi2ND6E1DEtMA",
      'consumer_secret' => "Bglu3sttmouKbOVdFZTMKCFTZlPV6IM8NBduDBD6UJU"
    );

    /** Note: Set the GET field BEFORE calling buildOauth(); **/
    $url = 'https://api.twitter.com/1.1/search/tweets.json';
    $getfield = '?q=' . $terms . '&lang=en-gb&result_type=' . $tweet_type . '&count=100' . $location;
    $requestMethod = 'GET';
    $twitter = new TwitterAPIExchange($settings);
    $result = $twitter->setGetfield($getfield)
       ->buildOauth($url, $requestMethod)
       ->performRequest();

    $res = json_decode($result);

    if ($res->statuses) {
      $results_array[] = $res->statuses;

      if ($params['search_terms']['bigall'] == 1) {

        $now = date('Y-m-d', strtotime('now'));

        for ($i=1; $i <= 8; $i++) {

          $now = date('Y-m-d', strtotime("$now - 1 day"));

          // $getfield = '?q=' . $terms . '&result_type=*recent&count=100&geocode=54.213861,-4.548340,576.7529226763561km&until=' . $now;

          $getfield = '?q=' . $terms . '&result_type=*recent&count=100&until=' . $now;
          $requestMethod = 'GET';
          $twitter = new TwitterAPIExchange($settings);
          $result = $twitter->setGetfield($getfield)
             ->buildOauth($url, $requestMethod)
             ->performRequest();

          $res = json_decode($result);
          $count = sizeof($res->statuses) - 1;
          $last_id = ($res->statuses[$count]->id - 1);
          $results_array[] = $res->statuses;

          $getfield = '?q=' . $terms . '&result_type=*popular&count=100&until=' . $now;
          $requestMethod = 'GET';
          $twitter = new TwitterAPIExchange($settings);
          $result = $twitter->setGetfield($getfield)
             ->buildOauth($url, $requestMethod)
             ->performRequest();

          $res = json_decode($result);
          $results_array[] = $res->statuses;

          // London
          $getfield = '?q=' . $terms . '&result_type=*popular&count=100&geocode=54.213861,-4.548340,576.7529226763561km&until=' . $now;
          $requestMethod = 'GET';
          $twitter = new TwitterAPIExchange($settings);
          $result = $twitter->setGetfield($getfield)
             ->buildOauth($url, $requestMethod)
             ->performRequest();

          $res = json_decode($result);
          $results_array[] = $res->statuses;


          // $getfield = '?q=' . $terms . '&result_type=*recent&count=100&geocode=37.718590,-101.953125,4022.1373212313893km&until=' . $now;
          // // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&max_id=' . $last_id;
          // $requestMethod = 'GET';
          // $twitter = new TwitterAPIExchange($settings);
          // $result = $twitter->setGetfield($getfield)
          //    ->buildOauth($url, $requestMethod)
          //    ->performRequest();

          // $res = json_decode($result);
          // $results_array[] = $res->statuses;

          // $getfield = '?q=' . $terms . '&result_type=*popular&count=100&geocode=37.718590,-101.953125,4022.1373212313893km&until=' . $now;
          // // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&max_id=' . $last_id;
          // $requestMethod = 'GET';
          // $twitter = new TwitterAPIExchange($settings);
          // $result = $twitter->setGetfield($getfield)
          //    ->buildOauth($url, $requestMethod)
          //    ->performRequest();

          // $res = json_decode($result);
          // $results_array[] = $res->statuses;


          // $getfield = '?q=' . $terms . '&result_type=*recent&count=100&until=' . $now;
          // // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&max_id=' . $last_id;
          // $requestMethod = 'GET';
          // $twitter = new TwitterAPIExchange($settings);
          // $result = $twitter->setGetfield($getfield)
          //    ->buildOauth($url, $requestMethod)
          //    ->performRequest();

          // $res = json_decode($result);
          // $results_array[] = $res->statuses;

          // $getfield = '?q=' . $terms . '&result_type=*popular&count=100&until=' . $now;
          // // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&max_id=' . $last_id;
          // $requestMethod = 'GET';
          // $twitter = new TwitterAPIExchange($settings);
          // $result = $twitter->setGetfield($getfield)
          //    ->buildOauth($url, $requestMethod)
          //    ->performRequest();

          // $res = json_decode($result);
          // $results_array[] = $res->statuses;

        }
      }

      print_r(json_encode($results_array));
    } else {
      print_r('error');
    }

  }

}

// function scraper_init() {

//   /** Set access tokens here - see: https://dev.twitter.com/apps/ **/
//   $settings = array(
//     'oauth_access_token' => "328416372-LKKl8TQMmcRLkbOuF31f4oNPcoKn4vKEBHqUmw9g",
//     'oauth_access_token_secret' => "7nzP4qbuNeqCvE7QUNHJ6AXdURubXie22JoiTk",
//     'consumer_key' => "C35vWXtEYi2ND6E1DEtMA",
//     'consumer_secret' => "Bglu3sttmouKbOVdFZTMKCFTZlPV6IM8NBduDBD6UJU"
//   );

//   $oo = 'fitness, blogger';
//   $terms = str_replace(',', ' ', $oo);
//   $terms = str_replace('  ', ' ', $terms);
//   $terms = urlencode($terms);

//   /** Set access tokens here - see: https://dev.twitter.com/apps/ **/
//     $settings = array(
//       'oauth_access_token' => "328416372-LKKl8TQMmcRLkbOuF31f4oNPcoKn4vKEBHqUmw9g",
//       'oauth_access_token_secret' => "7nzP4qbuNeqCvE7QUNHJ6AXdURubXie22JoiTk",
//       'consumer_key' => "C35vWXtEYi2ND6E1DEtMA",
//       'consumer_secret' => "Bglu3sttmouKbOVdFZTMKCFTZlPV6IM8NBduDBD6UJU"
//     );

//     /** Note: Set the GET field BEFORE calling buildOauth(); **/
//     $url = 'https://api.twitter.com/1.1/search/tweets.json';
//     $getfield = '?q=%40twitterapi';

//     // print_r($terms);

//     // around UK >
//     // 37.781157,-122.398720,1mi
//     // 54.213861,-4.548340,576.7529226763561km

//     // $results_array = array();

//     $search_type = 'apifier22';
//     if ($search_type == 'apifier') {

//       $now = date('Y-m-d', strtotime('now'));
//       $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=3&until=' . $now;
//       $requestMethod = 'GET';
//       $twitter = new TwitterAPIExchange($settings);
//       $result = $twitter->setGetfield($getfield)
//          ->buildOauth($url, $requestMethod)
//          ->performRequest();

//       $res = json_decode($result);
//       if ($res->statuses) {
//         $count = sizeof($res->statuses) - 1;
//         $last_id = ($res->statuses[$count]->id - 1);
//         $results_array[] = $res->statuses;
//         dpm($results_array);

//         foreach ($results_array[0] as $key => $tweet) {
//           dpm($tweet->user->screen_name);

//           $profile = 'https://twitter.com/' . $tweet->user->screen_name;
//           $headers = array(
//             'Content-Type' => 'application/json',
//           );
//           $data = '{"startUrls":[{"key": "TEST", "value": "'.$profile.'"}]}';
//           $url = 'https://api.apifier.com/v1/wzHqPfZhWtuPXpX3f/crawlers/Twitter%20Scraper/execute?token=5iijWrGbJetJZ2ZhhqvbcBWg7';
//           $apifier = drupal_http_request($url, $headers = array(), 'POST', $data);
//           dpm($apifier);

//           // curl -H
//           // "Content-Type: application/json"
//           // -X POST
//           // -d '{"startUrls":[{"key": "TEST", "value": "http://www.example.com"}]}'
//           // https://api.apifier.com/v1/wzHqPfZhWtuPXpX3f/crawlers/Twitter%20Scraper/execute?token=5iijWrGbJetJZ2ZhhqvbcBWg7

//         }
//       }

//       else {
//         dpm('err!');
//         print 'err';
//       }

//     }


//     // for ($i=1; $i <= 5; $i++) {

//     //   $now = date('Y-m-d', strtotime("$now - 1 day"));

//     //   $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=3&until=' . $now;
//     //   // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=3&max_id=' . $last_id;
//     //   $requestMethod = 'GET';
//     //   $twitter = new TwitterAPIExchange($settings);
//     //   $result = $twitter->setGetfield($getfield)
//     //      ->buildOauth($url, $requestMethod)
//     //      ->performRequest();

//     //   $res = json_decode($result);
//     //   $count = sizeof($res->statuses) - 1;
//     //   $last_id = ($res->statuses[$count]->id - 1);
//     //   $results_array[] = $res->statuses;
//     //   // dpm($last_id, 'last id...');
//     // }

//     // dpm($results_array);



//     // $getfield = '?q=' . $terms . '&count=100&lang=en-gb&geocode=54.213861,-4.548340,576.7529226763561km';

//     // $getfield = '?q=' . $terms . '&lang=en-gb&result_type=*recent&count=100&until=2016-06-16';
//     // $requestMethod = 'GET';
//     // $twitter = new TwitterAPIExchange($settings);
//     // $result = $twitter->setGetfield($getfield)
//     //    ->buildOauth($url, $requestMethod)
//     //    ->performRequest();


//     //    $res = json_decode($result);
//     // dpm($res);
// }
